<?php namespace ProcessWire;

/**
 *
 * Add Image URLs
 *
 * @author Robin Sallis
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class AddImageUrls extends WireData implements Module, ConfigurableModule {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => "Add Image URLs",
			'summary' => 'Allows images/files to be added to Image/File fields by pasting URLs.',
			'version' => '0.2.4',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/AddImageUrls',
			'icon' => 'picture-o',
			'autoload' => true,
			'requires' => 'ProcessWire>=3.0.0',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookMethod('Pagefiles::addFromUrl', $this, 'addFromUrl');
		$this->addHookAfter('InputfieldFile::render', $this, 'modifyInputfield');
		$this->addHookBefore('ProcessPageEdit::execute', $this, 'addDependencies');
		$this->addHookAfter('ProcessPageEdit::processInput', $this, 'processInput');
	}

	/**
	 * Modify inputfield
	 *
	 * @param HookEvent $event
	 */
	protected function modifyInputfield(HookEvent $event) {
		$process = $this->wire()->process;
		// Only for ProcessPageEdit or ProcessUser
		if($process != 'ProcessPageEdit' && $process != 'ProcessUser') return;
		// Only for edit mode of ProcessUser
		if($process == 'ProcessUser' && $this->wire()->input->urlSegment1 !== 'edit') return;

		$inputfield = $event->object;
		$is_image_inputfield = $inputfield instanceof InputfieldImage;
		$out = $event->return;
		$page = $inputfield->hasPage;
		$field = $inputfield->hasField;

		$button_text = $this->_('Paste URLs');
		if($is_image_inputfield) {
			$placeholder_text = $this->_('Paste URLs to images here, one per line…');
		} else {
			$placeholder_text = $this->_('Paste URLs to files here, one per line…');
		}

		$button = "<button class='url-upload-toggle ui-button ui-widget ui-corner-all ui-state-default ui-priority-secondary'><span class='ui-button-text'><i class='fa fa-clipboard'></i> $button_text</span></button>";
		$find = array("<span class='InputfieldImageValidExtensions", "<span class='InputfieldFileValidExtensions");
		$replace = array("$button<span class='InputfieldImageValidExtensions", "$button<span class='InputfieldFileValidExtensions");
		$out = str_replace($find, $replace, $out);
		$out .= "
<div class='url-upload-container'>
<textarea name='urlUpload*{$field->name}*{$page->id}' rows='2' placeholder='$placeholder_text'></textarea>
</div>
";
		$event->return = $out;
	}

	/**
	 * Add JS and CSS dependencies
	 *
	 * @param HookEvent $event
	 */
	protected function addDependencies(HookEvent $event) {
		$config = $this->wire()->config;

		// Return if ProcessPageEdit is being loaded via AJAX
		if($config->ajax) return;

		// Add JS and CSS dependencies
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->scripts->add($config->urls->{$this} . "{$this}.js?v={$version}");
		$config->styles->add($config->urls->{$this} . "{$this}.css?v={$version}");
	}

	/**
	 * Process URLs in $input
	 *
	 * @param HookEvent $event
	 */
	protected function processInput(HookEvent $event) {

		$form = $event->arguments(0);
		// Only for main Page Edit form
		if($form->name !== 'ProcessPageEdit') return;

		foreach($this->wire()->input->post as $key => $value) {

			// Ignore unrelated input
			if(substr($key, 0, 9) !== 'urlUpload' || empty($value)) continue;

			// Get variables from key name
			list($junk, $field_name, $page_id) = explode('*', $key);
			$field_name = $this->wire()->sanitizer->fieldName($field_name);
			$page = $this->wire()->pages->get((int) $page_id);
			$field = $this->wire()->fields->get($field_name);
			$field_value = $page->getUnformatted($field_name);

			// Skip if the user does not have edit access for the page and field
			$editable = false;
			if($page instanceof RepeaterPage) {
				// Check field and Repeater field are editable
				if(!$field->useRoles || $field->editable()) {
					$repeater_field = $page->getForField();
					if(!$repeater_field->useRoles || $repeater_field->editable()) $editable = true;
				}
			} else {
				// Check page and field are editable
				if($page->editable($field_name)) $editable = true;
			}
			if(!$editable) {
				$this->error( $this->_('You do not have permission to edit this field.') );
				continue;
			}

			// How many more uploads allowed?
			if($field->maxFiles == 1) {
				$remaining_uploads = 1; // Single image/file field is allowed to be overwritten
			} elseif($field->maxFiles) {
				$remaining_uploads = $field->maxFiles - count($field_value);
			} else {
				$remaining_uploads = 9999;
			}

			// Determine allowed extensions
			$allowed_extensions = explode(' ', $field->extensions);

			// Get array of URLs
			$urls = preg_split("/\r\n|\n|\r/", $value);

			$this->addUrlsToField(
				$page,
				$urls,
				$field,
				$field_value,
				$remaining_uploads,
				$allowed_extensions
			);

		}
	}

	/**
	 * Add image(s) through API using $field->addFromUrl($urls)
	 * 
	 * Can be a string with one or multiple URLs separated by a comma or an
	 * array of URLs
	 * 
	 * @param HookEvent $event
	 */
	protected function addFromUrl(HookEvent $event) {

		$urls = $event->arguments(0);
		if(empty($urls)) return;

		$page = $event->object->getPage();
		$field = $event->object->getField();
		$field_value = $page->getUnformatted($field->name);

		// How many more uploads allowed?
		if($field->maxFiles == 1) {
			$remaining_uploads = 1; // Single image/file field is allowed to be overwritten
		} elseif($field->maxFiles) {
			$remaining_uploads = $field->maxFiles - count($field_value);
		} else {
			$remaining_uploads = 9999;
		}

		// Determine allowed extensions
		$allowed_extensions = explode(' ', $field->extensions);

		// Get array of URLs
		if(is_string($urls)) {
			$urls = explode(",", trim($urls));
		} elseif(!is_array($urls)) {
			// if the URLs turns out to be neither a string nor an array, abort
			return;
		}

		$this->addUrlsToField(
			$page,
			$urls,
			$field,
			$field_value,
			$remaining_uploads,
			$allowed_extensions
		);
	}

	protected function addUrlsToField(
		Page $page,
		$urls,
		$field,
		$field_value,
		$remaining_uploads,
		$allowed_extensions
	) {

		$page->of(false);
		foreach($urls as $url) {
			$url = trim($url);
			// Break if the field is full
			if($remaining_uploads < 1) {
				$this->warning( sprintf($this->_('Max file upload limit reached for field "%s".'), $field->name) );
				break;
			}
			// Must be a valid URL
			if(!filter_var($url, FILTER_VALIDATE_URL)) {
				$this->error( sprintf($this->_('%s is not a valid URL.'), $url) );
				continue;
			}
			// Validate file extension if one exists
			$parsed_url = parse_url($url);
			if(empty($parsed_url['path'])) {
				$this->error( sprintf($this->_('The URL %s has no parsable path.'), $url) );
				continue;
			}
			$path_parts = pathinfo($parsed_url['path']);
			if(empty($path_parts['basename'])) {
				$this->error( sprintf($this->_('The URL %s has no parsable basename.'), $url) );
				continue;
			}
			$extension = isset($path_parts['extension']) ? $path_parts['extension'] : '';
			if($extension) {
				if(!in_array($extension, $allowed_extensions)) {
					$this->error( sprintf($this->_('%1$s is not an allowed extension for field "%2$s".'), $extension, $field->name) );
					continue;
				}
			} else {
				// Remote file has no extension, so download to temp directory
				$files = $this->wire()->files;
				$td = $files->tempDir($this->className);
				$td_path = (string) $td;
				$destination = $td_path . $path_parts['basename'];
				$success = @copy($url, $destination);
				if(!$success) {
					$this->error( sprintf($this->_('No file could be downloaded from URL %s'), $url) );
					continue;
				}
				$mime_type = mime_content_type($destination);
				$mime_mappings = [];
				$mapping_lines = preg_split('/[\r\n]+/', $this->mime_types);
				foreach($mapping_lines as $line) {
					$pieces = explode(':', $line, 2);
					if(count($pieces) < 2) continue;
					$mime_mappings[$pieces[0]] = $pieces[1];
				}
				$add_extension = isset($mime_mappings[$mime_type]) ? $mime_mappings[$mime_type] : '';
				// Add file extension if valid for the field
				if(in_array($add_extension, $allowed_extensions)) {
					$url = "$destination.$add_extension";
					$files->rename($destination, $url);
				} else {
					$this->error( sprintf($this->_('The remote file %1$s has no file extension and its MIME type does not correspond with a valid file extension for field "%2$s".'), $url, $field->name) );
					continue;
				}
			}

			// If it's a single image/file field and there's an existing image/file, remove it (as per the core upload behaviour)
			if($field->maxFiles == 1 && count($field_value)) $field_value->removeAll();
			// Create Pagefile
			if($field->type instanceof FieldtypeImage) {
				$pagefile = new Pageimage($field_value, $url);
				// Resize to maximum width/height if necessary
				if($field->maxWidth && $field->maxWidth < $pagefile->width || $field->maxHeight && $field->maxHeight < $pagefile->height) {
					$width = $field->maxWidth ?: 0;
					$height = $field->maxHeight ?: 0;
					if($width && $pagefile->width >= $pagefile->height) $height = 0;
					if($height && $pagefile->width < $pagefile->height) $width = 0;
					$sizer = new ImageSizer($pagefile->filename);
					$sizer->setUpscaling(false);
					$sizer->resize($width, $height);
				}
			} else {
				$pagefile = new Pagefile($field_value, $url);
			}

			// Add the Pagefile to the field
			$field_value->add($pagefile);
			// Decrement remaining uploads
			$remaining_uploads--;
		}
		// Save
		$page->save();
	}

	/**
	 * Save default mime types to config
	 */
	protected function saveDefaultMimeTypes() {
		$mime_types = <<<EOT
text/plain:txt
application/pdf:pdf
application/msword:docx
application/excel:xlsx
application/rtf:rtf
image/gif:gif
image/jpeg:jpg
image/png:png
image/svg+xml:svg
image/webp:webp
EOT;
		$this->wire()->modules->saveConfig($this->className, 'mime_types', $mime_types);
	}

	/**
	 * Install
	 */
	public function ___install() {
		// Save default mime types to config
		$this->saveDefaultMimeTypes();
	}

	/**
	 * Upgrade
	 *
	 * @param $fromVersion
	 * @param $toVersion
	 */
	public function ___upgrade($fromVersion, $toVersion) {
		// Upgrade from < v0.2.2: save default mime types to config
		if(version_compare($fromVersion, '0.2.2', '<')) {
			$this->saveDefaultMimeTypes();
		}
	}

	/**
	 * Config inputfields
	 *
	 * @param InputfieldWrapper $inputfields
	 */
	public function getModuleConfigInputfields($inputfields) {
		$modules = $this->wire()->modules;

		/* @var InputfieldTextarea $f */
		$f = $modules->InputfieldTextarea;
		$f_name = 'mime_types';
		$f->name = $f_name;
		$f->label = $this->_('MIME types');
		$f->description = $this->_('Enter MIME type > file extension mappings in the format "MIME type:file extension", one per line. File extensions should be lower case. These mappings are used when validating URLs to files that do not have file extensions.');
		$f->value = $this->$f_name;
		$inputfields->add($f);
	}

}
